### ISSUE TITLE
Empty charts and duplicate scrobbles with Libre.fm

### ISSUE THREAD

**Issue by AttacktoWin** [kawaiiDango/pano-scrobbler#558]
**Describe the bug**
I scrobble solely to Libre.fm in the app and while the recent plays is mostly accurate with no duplicates, my profile on Libre.fm shows numerous duplicates.

![Image](https://github.com/user-attachments/assets/590ea601-498b-469d-803b-8c8278ee2e2c)

I only noticed this after trying to resolve the charts tab going entirely blank a few months back.

![Image](https://github.com/user-attachments/assets/8fa983ea-de5b-4500-ab1f-4f06d0694578)

I have already tried force stopping and clearing cache, clearing all data, and fully reinstalling the app so this is most likely an issue with the API for getting charts from Libre.fm.

**Steps to Reproduce**
- Scrobble music to Libre.fm
- Open the app and go to the charts tab

**App version**
3.45

**Android version**
Android 15

**Additional info**
Reinstalling a prior version of the app does not fix the charts.

**Comment by AttacktoWin** [comment]
Looks like the duplicate scrobbles was an issue on Libre.fm's side based on this issue https://github.com/foocorp/hacienda/issues/71

**Comment by mattl** [comment]
This is back, but I am fixing it today in https://github.com/foocorp/hacienda/issues/71

**Comment by mattl** [comment]
And I've fixed it https://github.com/foocorp/end-times/commit/0a6932c1f08824e6e5a76b758b8900f51253a536

**Comment by AttacktoWin** [comment]
That solves the duplicate tracks, still having issues with getting charts in Pano

**Comment by mattl** [comment]
I don't know how Pano is generating those, but that's probably because they're turned off right now on Libre.fm too.

**Comment by AttacktoWin** [comment]
Gotcha, I was digging around the code and found [this file](https://github.com/kawaiiDango/pano-scrobbler/blob/main/composeApp/src/commonMain/kotlin/com/arn/scrobble/api/lastfm/Lastfm.kt) which seems to be where the data is grabbed. If getting a user's top tracks is turned off on your end then it makes sense for it to be broken here.

**Comment by mattl** [comment]
Maybe someone can help me figure out (ie. tell me) the URL it's hitting on my end and I'll see what I can do.

It's been a long day.

**Comment by AttacktoWin** [comment]
Finally managed to parse that class, kotlin is entirely foreign to me. Looks like it's hitting a url similar to this with the values for username, api key, and auth key replaced with actual values
https://libre.fm/2.0/?user=username&format=json&api_key=api_key&sk=auth_key&method=user.getTopArtists

**Comment by kawaiiDango** [comment]
Just woke up.

It hits 

```
curl 'https://libre.fm/2.0/?user=kawaiiDango&limit=50&format=json&api_key=panoScrobbler&sk=mySessionKey&period=12month&page=1&method=user.getTopTracks' \
  -H 'accept: application/json' \
  -H 'accept-charset: UTF-8' \
  -H 'accept-encoding: gzip' \
  -H 'connection: Keep-Alive' \
  -H 'host: libre.fm' \
  -H 'user-agent: Pano Scrobbler 3.45 - 2025, Mar 20 DEBUG' \
  --compressed
```

It outputs the sql query in \<\!-- --> comments and then the json data after that. So the json parser cannot parse that.

**Comment by mattl** [comment]
Let me take a look in a bit and see if I can stop that. I’ve been doing a lot of work on the site recently.

**Comment by mattl** [comment]
Fixed it. Let me know if this magically fixes things for you @AttacktoWin and thanks @kawaiiDango :)

**Comment by kawaiiDango** [comment]
Yeah it does. Thanks.
